"""Generate two self-contained, schema-valid GPJSON 4.1 example Features that
share ONE protocol/orchestration vocabulary but carry structurally different
payloads:

  examples/microseismic_example.json   seismic.trace  waveform gather (S1/S2)
  examples/insar_example.json          insar.deformation  Grid2D LOS stack

The InSAR example uses a compact 32x32 x 8-epoch grid purely to keep the file
small; the full-size 64x64 x 16 scenes used in the paper are produced by
experiments/exp_insar.py. Both documents embed the same core quality block,
Pipeline Profile and thin orch_intent block, demonstrating the cross-modality
unification. Run:  python -m scripts.gen_examples
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import jsonschema  # noqa: E402

from gpjson41 import write_feature  # noqa: E402
from synth import MSConfig, generate_window, make_station_network  # noqa: E402
from synth.microseismic import reference_signal_rms  # noqa: E402
from synth.insar import InSARConfig, generate_scene as gen_insar  # noqa: E402


def main():
    outdir = ROOT / "examples"
    outdir.mkdir(parents=True, exist_ok=True)
    schema = json.loads((ROOT / "gpjson41" / "schema_feat.json").read_text(
        encoding="utf-8"))

    # --- microseismic: 8-station, 5 s, 1 kHz waveform gather --------------
    mcfg = MSConfig()
    stations = make_station_network(mcfg, seed=0)
    ref = reference_signal_rms(mcfg, stations)
    f_ms, _ = generate_window(mcfg, stations, 20.0, 1.0, True,
                              np.random.default_rng(11), ref)
    p_ms = outdir / "microseismic_example.json"
    write_feature(str(p_ms), f_ms)
    jsonschema.validate(f_ms, schema)

    # --- InSAR: compact single-track LOS stack with a Mogi source ---------
    icfg = InSARConfig(nx=32, ny=32, n_epochs=8,
                       xlim=(-200.0, 200.0), ylim=(-200.0, 200.0),
                       depth_range=(350.0, 700.0),
                       peak_los_range_mm=(15.0, 30.0))
    f_in, truth = gen_insar(icfg, 0.85, True, np.random.default_rng(12), 0,
                            goal="anomaly_confirmation", priority="normal",
                            latency_budget_s=86400.0)
    f_in["properties"]["example_note"] = (
        "Compact illustrative instance (32x32 x 8 epochs); full-size scenes "
        "are generated by experiments/exp_insar.py")
    p_in = outdir / "insar_example.json"
    write_feature(str(p_in), f_in)
    jsonschema.validate(f_in, schema)

    for p, kind in ((p_ms, f_ms["properties"].get("kind")),
                    (p_in, f_in["properties"].get("kind"))):
        print(f"{p.name:32s} {p.stat().st_size/1024:8.1f} KB  kind={kind}")
    print("Both examples validate against gpjson41/schema_feat.json")


if __name__ == "__main__":
    main()
